version: '3.8'

services:
  gocoder:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
    environment:
      - DATABASE=/app/database/geocoder.gpkg
      - ENABLE_FORWARD=true
      - ENABLE_REVERSE=true
    command: ["./gocoder", "server"]
    restart: unless-stopped

  # Optional: Add a generation service that runs once
  gocoder-generate:
    image: ghcr.io/hstin-de/gocoder:latest
    volumes:
      - ./data:/data
      - ./database:/app/database
    environment:
      - PLANET=/data/germany-latest.osm.pbf
      - WHOS_ON_FIRST=/data/whosonfirst-data-admin-latest.db
      - WIKIMEDIA_IMPORTANCE=/data/wikimedia-importance.csv.gz
      - OUTPUT=/app/database/germany.gpkg
    command: ["./gocoder", "generate"]
    profiles:
      - generate